### ISSUE TITLE
https://aws.amazon.com/elasticloadbalancing/features/#Product_comparisons

### ISSUE THREAD

**Issue by manuelh2410** [awsdocs/elb-user-quide#1]
![Capture](https://user-images.githubusercontent.com/50540203/89715144-26f9f200-d9a4-11ea-9884-d2729bd5b2ab.JPG)
https://aws.amazon.com/elasticloadbalancing/features/#Product_comparisons

The table states that the Network Load Balancer operates at Layer 7 . 
Don't think this is correct.

The issue seems to be in the page source. Specifically  with HTML element :

`<td colspan="4" height="19" width="697" style="text-align: center;"><b>Layer 7</b></td>`

I believe you can fix this by modifying the page source as follows : 

           <tr>
           <td height="19" width="178">OSI Layer Functionality</td> 
           <td width="158">Layer 7</td> 
           <td width="152">Layer 4</td> 
           <td width="209">Both</td> 
          </tr>
==

Regards ,

Manuel Hubbard

**Comment by julieso** [comment]
Thanks for reporting this. I also saw that you provided the same feedback through the feedback link on the HTML docs. I forwarded that feedback to the marketing team so they can update the site.

**Comment by manuelh2410** [comment]
https://aws.amazon.com/elasticloadbalancing/features/#Product_comparisons

The table contains an error with regards to VPC security group option for the  "Network Load Balancer"

The issue seems to be in the page source . Specifically  with HTML element :

`<tr> <td colspan="4" height="19" width="697" style="text-align: center;"><b>Security</b></td> </tr>`

I believe you can fix this by modifying the page source as follows : 

           <tr> 
           <td height="60" width="178">Security Groups</td> 
           <td width="158">✔</td> 
           <td width="152">&nbsp;</td> 
           <td width="209">✔</td> 
          </tr>
==


Regards,

Manuel Hubbard
