### ISSUE TITLE
# New Issue on  https://aws.amazon.com/elasticloadbalancing/features/#Product_comparisons

### ISSUE THREAD

**Issue by manuelh2410** [awsdocs/elb-user-quide#2]
Good Day,

I would like to request an alteration to the table depicted in the following link : 
https://aws.amazon.com/elasticloadbalancing/features/#Product_comparisons

I see that "layer 7" and "Security" are supposed to be separate sections in the table. 
I don't think this is clear in the current version of the table. 

Instead of indicating a separate section, It actually looks like these two words are misaligned (offset column data) .

the elements in question are : 
`<td colspan="4" height="19" width="697" style="text-align: center;"><b>Layer 7</b></td>`
`<tr> <td colspan="4" height="19" width="697" style="text-align: center;"><b>Security</b></td> </tr>`

Maybe this can be changed to : 
`<td colspan="4" height="19" width="697" style="text-align: center;"><b>Layer 7 Features</b></td>`

`<tr> <td colspan="4" height="19" width="697" style="text-align: center;"><b>Security Features</b></td> </tr>`

Just to ensure that its clear that these two words indicate a subsection of the table. 

Regards,

Manuel Hubbard
![New_Table](https://user-images.githubusercontent.com/50540203/89810217-0022f380-db3d-11ea-97e6-b0a5bb73548f.JPG)

**Comment by julieso** [comment]
Thanks. I have passed your feedback to the marketing team.
