### ISSUE TITLE
Outdated architecture icons in how-elastic-load-balancing-works.md

### ISSUE THREAD

**Issue by megaproaktiv** [awsdocs/elb-user-quide#4]
In how-elastic-load-balancing-works.md older icons that the current https://aws.amazon.com/architecture/icons/ are used.
Also, the orange icon for the classic load balancer is used instead of the icon for Elastic Network Interfaces.
I get the concept that there are two  Load Balancer "nodes", but the diagram suggests that there are two load balancers.

In AWS Training Architecting on AWS  and Systems operations, the Load Balancer icons in diagrams are clearly distinguished from the ENI icons

**Comment by julieso** [comment]
Thanks for the suggestion. I replaced the load balancer icons with network interface icons.
